export const endpoints = {
  system: {
    health: "/health",
  },
  auth: {
    register: "/register",
    login: "/login",
    me: "/me",
    refresh: "/refresh",
    logout: "/logout",
    verify: "/verify-email",
    forgot: "/forgot-password",
    reset: "/reset-password",
  },
  contact: {
    create: "/contact",
  },
  history: {
    list: "/history",
    add: "/history",
  },
  profile: {
    me: "/profile/me",
    update: "/profile",
    location: "/profile/location",
    availability: "/profile/availability",
    preferences: "/profile/preferences",
    byId: (userId) => `/profile/${userId}`,
  },
  matching: {
    suggestions: "/matching/suggestions",
    like: "/matching/like",
    unlike: "/matching/unlike",
    reject: "/matching/reject",
    mutual: "/matching/mutual",
    block: "/matching/block",
    rejected: "/matching/rejected",
    relike: "/matching/relike",
  },
  subscription: {
    create: "/subscriptions/create-checkout-session",
    status: "/subscriptions/status",
    cancel: "/subscriptions/cancel",
    portal: "/subscriptions/customer-portal",
  },
  chat: {
    send: "/chat/send",
    history: "/chat/history",
    escalate: "/chat/escalate",
    aiConversations: "/chat/ai-conversations",
    deleteAiConversation: (conversationId) => `/chat/ai-conversation/${conversationId}`,
  },
  supportTickets: {
    list: "/admin/support-tickets",
    byId: (ticketId) => `/admin/support-tickets/${ticketId}`,
    reply: (ticketId) => `/admin/support-tickets/${ticketId}/reply`,
    resolve: (ticketId) => `/admin/support-tickets/${ticketId}/resolve`,
    reopen: (ticketId) => `/admin/support-tickets/${ticketId}/reopen`,
    assign: (ticketId) => `/admin/support-tickets/${ticketId}/assign`,
    stats: "/admin/support-tickets/stats",
  },
  notifications: {
    list: "/notifications",
    add: "/notifications",
    markAsRead: (notificationId) => `/notifications/${notificationId}/read`,
    markAllRead: "/notifications/read-all",
    delete: (notificationId) => `/notifications/${notificationId}`,
    clearAll: "/notifications/clear",
    trackClick: (notificationId) => `/notifications/${notificationId}/click`,
    clickStats: "/notifications/stats/clicks",
  },
  analytics: {
    weekly: "/analytics/weekly",
    adminNotifications: "/analytics/admin/notifications",
  },
  challenges: {
    list: "/challenges",
    stats: "/challenges/stats",
    byId: (id) => `/challenges/${id}`,
    create: "/challenges",
    accept: (id) => `/challenges/${id}/accept`,
    decline: (id) => `/challenges/${id}/decline`,
    cancel: (id) => `/challenges/${id}/cancel`,
    congratulate: "/challenges/congratulate",
    submitResult: (id) => `/challenges/${id}/submit-result`,
  },
  xpRedemption: {
    eligibility: "/xp-redemption/eligibility",
    redeem: "/xp-redemption/redeem",
    history: "/xp-redemption/history",
  },
  partners: {
    list: "/partners",
    byId: (id) => `/partners/${id}`,
    myRewards: "/partners/user/my-rewards",
    checkRedemption: (partnerId) => `/partners/user/check/${partnerId}`,
    redeem: (id) => `/partners/${id}/redeem`,
    // Admin
    adminList: "/partners/admin/all",
    adminCreate: "/partners/admin",
    adminUpdate: (id) => `/partners/admin/${id}`,
    adminDelete: (id) => `/partners/admin/${id}`,
    adminStats: (id) => `/partners/admin/${id}/stats`,
  },
  nutrition: {
    log: "/nutrition/log",
    logRecipe: "/nutrition/log-recipe",
    daily: (date) => `/nutrition/daily/${date}`,
    updateLog: (id) => `/nutrition/log/${id}`,
    deleteLog: (id) => `/nutrition/log/${id}`,
    summaryDaily: (date) => `/nutrition/summary/daily/${date}`,
    summaryWeekly: "/nutrition/summary/weekly",
    summaryMonthly: "/nutrition/summary/monthly",
    goals: "/nutrition/goals",
  },
  health: {
    sync: "/health/sync",
  },
  social: {
    feed: "/social/feed",
    stats: "/social/stats",
    search: "/social/search",
    follow: (userId) => `/social/follow/${userId}`,
    unfollow: (userId) => `/social/follow/${userId}`,
    followers: (userId) => `/social/followers/${userId}`,
    following: (userId) => `/social/following/${userId}`,
    userProfile: (userId) => `/social/users/${userId}`,
    likePost: (targetId) => `/social/feed/${targetId}/like`,
    sendMessage: (userId) => `/social/message/${userId}`,
    getComments: (postId) => `/social/feed/${postId}/comments`,
    addComment: (postId) => `/social/feed/${postId}/comments`,
    deleteComment: (postId, commentId) => `/social/feed/${postId}/comments/${commentId}`,
  },
  bodyComposition: {
    summary: "/body-composition/summary",
    trend: "/body-composition/trend",
    logWeight: "/body-composition/weight",
    weightHistory: "/body-composition/weight",
    deleteWeight: (id) => `/body-composition/weight/${id}`,
    metrics: "/body-composition/metrics",
  },
  sharedSessions: {
    invite: "/shared-sessions/invite",
    respond: (id) => `/shared-sessions/${id}/respond`,
    active: "/shared-sessions/active",
    history: "/shared-sessions/history",
    byMatch: (matchId) => `/shared-sessions/by-match/${matchId}`,
    byId: (id) => `/shared-sessions/${id}`,
    addExercise: (id) => `/shared-sessions/${id}/exercises`,
    removeExercise: (id, order) => `/shared-sessions/${id}/exercises/${order}`,
    reorderExercises: (id) => `/shared-sessions/${id}/exercises/reorder`,
    start: (id) => `/shared-sessions/${id}/start`,
    progress: (id) => `/shared-sessions/${id}/progress`,
    exerciseData: (id) => `/shared-sessions/${id}/exercise-data`,
    end: (id) => `/shared-sessions/${id}/end`,
    cancel: (id) => `/shared-sessions/${id}/cancel`,
  },
  barcode: {
    lookup: (barcode) => `/barcode/${barcode}`,
  },
};
export default endpoints;