export const endpoints = {
  system: {
    health: "/health",
  },
  auth: {
    register: "/register",
    login: "/login",
    me: "/me",
    updateProfile: "/update-profile",
    refresh: "/refresh",
    logout: "/logout",
    verify: "/verify-email",
    forgot: "/forgot-password",
    reset: "/reset-password",
    resendVerification: "/resend-verification",
    setPassword: "/auth/set-password",
    changePassword: "/change-password",
    requestEmailChange: "/request-email-change",
  },
  contact: {
    create: "/contact",
  },
  history: {
    list: "/history",
    add: "/history",
    summary: "/history/summary",
  },
  profile: {
    me: "/profile/me",
    update: "/profile",
    location: "/profile/location",
    availability: "/profile/availability",
    preferences: "/profile/preferences",
    byId: (userId) => `/profile/${userId}`,
    onboarding: "/profile/onboarding",
  },
  matching: {
    suggestions: "/matching/suggestions",
    like: "/matching/like",
    unlike: "/matching/unlike",
    reject: "/matching/reject",
    mutual: "/matching/mutual",
    block: "/matching/block",
    rejected: "/matching/rejected",
    relike: "/matching/relike",
  },
  subscription: {
    create: "/subscriptions/create-checkout-session",
    status: "/subscriptions/status",
    cancel: "/subscriptions/cancel",
    portal: "/subscriptions/customer-portal",
  },
  chat: {
    send: "/chat/send",
    history: "/chat/history",
    escalate: "/chat/escalate",
    aiConversations: "/chat/ai-conversations",
    deleteAiConversation: (conversationId) => `/chat/ai-conversation/${conversationId}`,
  },
  supportTickets: {
    list: "/admin/support-tickets",
    byId: (ticketId) => `/admin/support-tickets/${ticketId}`,
    reply: (ticketId) => `/admin/support-tickets/${ticketId}/reply`,
    resolve: (ticketId) => `/admin/support-tickets/${ticketId}/resolve`,
    reopen: (ticketId) => `/admin/support-tickets/${ticketId}/reopen`,
    assign: (ticketId) => `/admin/support-tickets/${ticketId}/assign`,
    stats: "/admin/support-tickets/stats",
  },
  notifications: {
    list: "/notifications",
    add: "/notifications",
    markAsRead: (notificationId) => `/notifications/${notificationId}/read`,
    markAllRead: "/notifications/read-all",
    delete: (notificationId) => `/notifications/${notificationId}`,
    clearAll: "/notifications/clear",
    trackClick: (notificationId) => `/notifications/${notificationId}/click`,
    clickStats: "/notifications/stats/clicks",
  },
  analytics: {
    weekly: "/analytics/weekly",
    adminNotifications: "/analytics/admin/notifications",
  },
  challenges: {
    list: "/challenges",
    stats: "/challenges/stats",
    leaderboard: "/challenges/leaderboard",
    byId: (id) => `/challenges/${id}`,
    create: "/challenges",
    accept: (id) => `/challenges/${id}/accept`,
    decline: (id) => `/challenges/${id}/decline`,
    cancel: (id) => `/challenges/${id}/cancel`,
    congratulate: "/challenges/congratulate",
    submitResult: (id) => `/challenges/${id}/submit-result`,
  },
  chatUpload: "/chat-upload",
  xpRedemption: {
    eligibility: "/xp-redemption/eligibility",
    redeem: "/xp-redemption/redeem",
    history: "/xp-redemption/history",
  },
  partners: {
    list: "/partners",
    byId: (id) => `/partners/${id}`,
    myRewards: "/partners/user/my-rewards",
    checkRedemption: (partnerId) => `/partners/user/check/${partnerId}`,
    redeem: (id) => `/partners/${id}/redeem`,
    // Admin
    adminList: "/partners/admin/all",
    adminCreate: "/partners/admin",
    adminUpdate: (id) => `/partners/admin/${id}`,
    adminDelete: (id) => `/partners/admin/${id}`,
    adminStats: (id) => `/partners/admin/${id}/stats`,
  },
  matchChat: {
    conversations: "/match-chat/conversations",
    unreadCount: "/match-chat/unread-count",
    conversation: (matchId) => `/match-chat/conversation/${matchId}`,
    socialConversation: (userId) => `/match-chat/social/${userId}`,
    messages: (conversationId) => `/match-chat/${conversationId}/messages`,
    markAsRead: (conversationId) => `/match-chat/${conversationId}/read`,
    deleteMessage: (messageId) => `/match-chat/messages/${messageId}`,
    block: (conversationId) => `/match-chat/${conversationId}/block`,
    delete: (conversationId) => `/match-chat/conversation/${conversationId}`,
    settings: (conversationId) => `/match-chat/conversation/${conversationId}/settings`,
  },
  exercises: {
    list: "/exercises",
    categories: "/exercises/categories",
    muscles: "/exercises/muscles",
    popular: "/exercises/popular",
    byCategory: (category) => `/exercises/category/${category}`,
    byMuscle: (muscle) => `/exercises/muscle/${muscle}`,
    byId: (idOrSlug) => `/exercises/${idOrSlug}`,
  },
  workouts: {
    sessions: "/workouts/sessions",
    sessionById: (id) => `/workouts/sessions/${id}`,
    dailySummary: "/workouts/summary/daily",
    lastWeekSession: "/workouts/last-week-session",
  },
  recipes: {
    list: "/recipes",
    featured: "/recipes/featured",
    trending: "/recipes/trending",
    suggestions: "/recipes/suggestions",
    liked: "/recipes/liked",
    saved: "/recipes/saved",
    myRecipes: "/recipes/user/my-recipes",
    myRecipeById: (id) => `/recipes/user/${id}`,
    create: "/recipes/user",
    update: (id) => `/recipes/user/${id}`,
    delete: (id) => `/recipes/user/${id}`,
    like: (id) => `/recipes/${id}/like`,
    save: (id) => `/recipes/${id}/save`,
    rate: (id) => `/recipes/${id}/rate`,
    propose: (id) => `/recipes/user/${id}/propose`,
    unpublish: (id) => `/recipes/user/${id}/unpublish`,
    byId: (id) => `/recipes/${id}`,
    similar: (id) => `/recipes/${id}/similar`,
  },
  upload: {
    profilePhoto: "/upload/profile-photo",
  },
  social: {
    feed: "/social/feed",
    stats: "/social/stats",
    search: "/social/search",
    follow: (userId) => `/social/follow/${userId}`,
    unfollow: (userId) => `/social/follow/${userId}`,
    followers: (userId) => `/social/followers/${userId}`,
    following: (userId) => `/social/following/${userId}`,
    userProfile: (userId) => `/social/users/${userId}`,
    likePost: (targetId) => `/social/feed/${targetId}/like`,
    sendMessage: (userId) => `/social/message/${userId}`,
    getComments: (postId) => `/social/feed/${postId}/comments`,
    addComment: (postId) => `/social/feed/${postId}/comments`,
    deleteComment: (postId, commentId) => `/social/feed/${postId}/comments/${commentId}`,
  },
  leaderboard: {
    status: "/leaderboard/status",
    list: "/leaderboard",
    userRank: (userId) => `/leaderboard/user/${userId}/rank`,
    optIn: "/leaderboard/opt-in",
    optOut: "/leaderboard/opt-out",
    refreshProfile: "/leaderboard/refresh-profile",
  },
  programs: {
    // Public
    public: "/programs/public",
    byId: (id) => `/programs/${id}`,
    // User (Premium required)
    myPrograms: "/programs/user/my-programs",
    favorites: "/programs/favorites",
    history: "/programs/history/sessions",
    // CRUD (Premium)
    create: "/programs",
    update: (id) => `/programs/${id}`,
    delete: (id) => `/programs/${id}`,
    // Actions (Premium)
    start: (id) => `/programs/${id}/start`,
    recordCompletion: (id) => `/programs/${id}/record-completion`,
    rate: (id) => `/programs/${id}/rate`,
    favorite: (id) => `/programs/${id}/favorite`,
    propose: (id) => `/programs/${id}/propose`,
    unpublish: (id) => `/programs/${id}/unpublish`,
  },
  nutrition: {
    log: "/nutrition/log",
    logRecipe: "/nutrition/log-recipe",
    daily: (date) => `/nutrition/daily/${date}`,
    updateLog: (id) => `/nutrition/log/${id}`,
    deleteLog: (id) => `/nutrition/log/${id}`,
    summaryDaily: (date) => `/nutrition/summary/daily/${date}`,
    summaryWeekly: "/nutrition/summary/weekly",
    summaryMonthly: "/nutrition/summary/monthly",
    goals: "/nutrition/goals",
    carousel: (date) => `/nutrition/carousel/${date}`,
    weekBar: "/nutrition/week-bar",
    scansPlats: "/nutrition/scans/plats",
    scansIngredients: "/nutrition/scans/ingredients",
    deleteScan: (type, id) => `/nutrition/scans/${type}/${id}`,
  },
  health: {
    sync: "/health/sync",
  },
  bodyComposition: {
    summary: "/body-composition/summary",
    trend: "/body-composition/trend",
    logWeight: "/body-composition/weight",
    weightHistory: "/body-composition/weight",
    deleteWeight: (id) => `/body-composition/weight/${id}`,
    metrics: "/body-composition/metrics",
  },
  barcode: {
    lookup: (barcode) => `/barcode/${barcode}`,
  },
  biorhythm: {
    syncSleep: "/biorhythm/sync-sleep",
    readiness: "/biorhythm/readiness",
    readinessHistory: "/biorhythm/readiness/history",
    sleep: (date) => `/biorhythm/sleep/${date}`,
    sleepHistory: "/biorhythm/sleep/history",
  },
};

export default endpoints;
